markdown: rdiscount
title: KanjiVG
url: http://kanjivg.tagaini.net
author: Ulrich Apel
project-links:
- text: Home
  url: /index.html
- text: Download
  url: /download.html
- text: Format
  url: /format.html
- text: Conventions
  url: /conventions.html
- text: Internationalization
  url: /internationalization.html
- text: Listing
  url: /listing.html
- text: Issues
  url: https://github.com/Gnurou/kanjivg/issues
community-links:
- text: Mailing list
  url: http://groups.google.com/group/kanjivg
- text: Projects using KanjiVG
  url: /projects.html
tool-links:
- text: Viewer
  url: /viewer.html
